In [1]:
import torch.nn as nn
import torch
from osgeo import gdal
import cv2
import math
import glob

In [2]:
content_criterion = nn.MSELoss()

In [8]:
image1 = r"E:\SijinLi\test\patch\0.tif"
datasets = gdal.Open(image1)
high = datasets.GetRasterBand(1).ReadAsArray()
low = cv2.resize(high, (250, 250), interpolation=cv2.INTER_NEAREST)
low1 = cv2.resize(high, (250, 250), interpolation=cv2.INTER_LINEAR)
lowhigh = cv2.resize(low, (500, 500), interpolation=cv2.INTER_NEAREST)

In [9]:
high

array([[4284.3657, 4302.094 , 4317.992 , ..., 3342.1501, 3358.794 ,
        3373.5566],
       [4301.9766, 4318.546 , 4333.636 , ..., 3346.638 , 3363.7314,
        3378.075 ],
       [4320.047 , 4334.3364, 4348.879 , ..., 3357.2678, 3375.7224,
        3389.0486],
       ...,
       [4807.385 , 4802.665 , 4785.7695, ..., 3296.6367, 3301.509 ,
        3308.2695],
       [4815.3833, 4810.93  , 4794.4043, ..., 3282.3953, 3281.5073,
        3290.7476],
       [4823.372 , 4819.6045, 4805.174 , ..., 3261.6367, 3261.2112,
        3273.9172]], dtype=float32)

In [10]:
lowhigh

array([[4284.3657, 4284.3657, 4317.992 , ..., 3325.9617, 3358.794 ,
        3358.794 ],
       [4284.3657, 4284.3657, 4317.992 , ..., 3325.9617, 3358.794 ,
        3358.794 ],
       [4320.047 , 4320.047 , 4348.879 , ..., 3340.8113, 3375.7224,
        3375.7224],
       ...,
       [4798.3813, 4798.3813, 4776.6406, ..., 3286.0964, 3324.5383,
        3324.5383],
       [4815.3833, 4815.3833, 4794.4043, ..., 3279.903 , 3281.5073,
        3281.5073],
       [4815.3833, 4815.3833, 4794.4043, ..., 3279.903 , 3281.5073,
        3281.5073]], dtype=float32)

In [8]:
low1

array([[4301.7456, 4333.834 , 4366.349 , ..., 3309.8105, 3336.2622,
        3368.5393],
       [4336.518 , 4364.799 , 4397.1387, ..., 3334.212 , 3358.047 ,
        3391.5503],
       [4370.5854, 4393.785 , 4431.0947, ..., 3375.769 , 3395.705 ,
        3426.7444],
       ...,
       [4781.8486, 4753.244 , 4710.928 , ..., 3255.1506, 3308.3198,
        3354.8176],
       [4800.518 , 4771.475 , 4731.4043, ..., 3253.7075, 3294.1094,
        3316.259 ],
       [4817.3223, 4791.2065, 4758.5254, ..., 3255.3047, 3271.879 ,
        3276.8457]], dtype=float32)

In [ ]:
image1 = r"E:\SijinLi\test\patch\0.tif"
datasets = gdal.Open(image1)
high = datasets.GetRasterBand(1).ReadAsArray()
math.sqrt(content_criterion(torch.tensor(high),torch.tensor(lowhigh)))

28.48229216191834

In [32]:
high

array([[4284.3657, 4302.094 , 4317.992 , ..., 3342.1501, 3358.794 ,
        3373.5566],
       [4301.9766, 4318.546 , 4333.636 , ..., 3346.638 , 3363.7314,
        3378.075 ],
       [4320.047 , 4334.3364, 4348.879 , ..., 3357.2678, 3375.7224,
        3389.0486],
       ...,
       [4807.385 , 4802.665 , 4785.7695, ..., 3296.6367, 3301.509 ,
        3308.2695],
       [4815.3833, 4810.93  , 4794.4043, ..., 3282.3953, 3281.5073,
        3290.7476],
       [4823.372 , 4819.6045, 4805.174 , ..., 3261.6367, 3261.2112,
        3273.9172]], dtype=float32)

In [22]:
lowhigh

array([[4284.3657, 4302.094 , 4317.992 , ..., 3342.1501, 3358.794 ,
        3373.5566],
       [4301.9766, 4318.546 , 4333.636 , ..., 3346.638 , 3363.7314,
        3378.075 ],
       [4320.047 , 4334.3364, 4348.879 , ..., 3357.2678, 3375.7224,
        3389.0486],
       ...,
       [4807.385 , 4802.665 , 4785.7695, ..., 3296.6367, 3301.509 ,
        3308.2695],
       [4815.3833, 4810.93  , 4794.4043, ..., 3282.3953, 3281.5073,
        3290.7476],
       [4823.372 , 4819.6045, 4805.174 , ..., 3261.6367, 3261.2112,
        3273.9172]], dtype=float32)

In [26]:
image2 = r"E:\Chenkai\cao_test2\a1\新建文件夹\1.tif"
datasets = gdal.Open(image2)
band2 = datasets.GetRasterBand(1).ReadAsArray()

In [27]:
content_criterion(torch.tensor(band2),torch.tensor(band))

tensor(0.5052)

In [32]:
cv2.resize(band, (128, 128), interpolation=cv2.INTER_LINEAR)

array([[1040.  , 1039.5 , 1039.  , ..., 1098.25, 1097.  , 1097.25],
       [1043.25, 1042.25, 1041.5 , ..., 1099.  , 1099.25, 1099.5 ],
       [1048.  , 1047.  , 1045.  , ..., 1100.5 , 1103.  , 1103.75],
       ...,
       [1084.25, 1085.5 , 1087.5 , ..., 1169.75, 1171.  , 1170.75],
       [1081.  , 1082.5 , 1085.  , ..., 1173.75, 1174.5 , 1173.75],
       [1079.  , 1081.  , 1083.5 , ..., 1178.5 , 1178.5 , 1177.5 ]],
      dtype=float32)

In [31]:
a = cv2.resize(band, (128, 128), interpolation=cv2.INTER_LINEAR)
cv2.resize(a , (256, 256), interpolation=cv2.INTER_NEAREST)

array([[1040.  , 1040.  , 1039.5 , ..., 1097.  , 1097.25, 1097.25],
       [1040.  , 1040.  , 1039.5 , ..., 1097.  , 1097.25, 1097.25],
       [1043.25, 1043.25, 1042.25, ..., 1099.25, 1099.5 , 1099.5 ],
       ...,
       [1081.  , 1081.  , 1082.5 , ..., 1174.5 , 1173.75, 1173.75],
       [1079.  , 1079.  , 1081.  , ..., 1178.5 , 1177.5 , 1177.5 ],
       [1079.  , 1079.  , 1081.  , ..., 1178.5 , 1177.5 , 1177.5 ]],
      dtype=float32)

In [11]:
TfaFolder = "E:\\CCHHYY\\超分\\大修\\添加实验\\tfrsa\\DEM"
ReferenceFolder = r"E:\SijinLi\test\patch"
Tfa = glob.glob(TfaFolder+"//*.tif")
Ref = glob.glob(ReferenceFolder+"//*.tif")
content_criterion = nn.MSELoss()

In [12]:
l = 0.0
for i in range(len(Tfa)):
    image1 = TfaFolder + "\\" + str(i) + ".tif"
    image2 = ReferenceFolder + "\\" + str(i) + ".tif"
    datasets1 = gdal.Open(image1)
    datasets2 = gdal.Open(image2)
    high1 = datasets1.GetRasterBand(1).ReadAsArray()
    high2 = datasets2.GetRasterBand(1).ReadAsArray()
    l += math.sqrt(content_criterion(torch.tensor(high1),torch.tensor(high2)))

In [14]:
l/16

6.579429119179908

In [ ]:
123